import type { VocabularyTable } from './vocabulary'

/**
 * Назви комплектації, які willhaben віддає німецькою.
 *
 * Список зібраний з усіх 99 оголошень дилера станом на 2026-07-22 і закритий:
 * тест перевіряє, що записів рівно 115 і що жоден не лишився без перекладу.
 * Якщо willhaben додасть нову назву, `translate` покаже її німецькою —
 * клієнт побачить чуже слово, але не порожнє місце.
 */
export const EQUIPMENT: VocabularyTable = {
  '2-Zonen-Klimaautomatik': { en: '2-zone climate control', tr: '2 bölgeli otomatik klima' },
  '3-Zonen-Klimaautomatik': { en: '3-zone climate control', tr: '3 bölgeli otomatik klima' },
  '360° Kamera': { en: '360° camera', tr: '360° kamera' },
  '4-Zonen-Klimaautomatik': { en: '4-zone climate control', tr: '4 bölgeli otomatik klima' },
  'ABS': { en: 'ABS', tr: 'ABS' },
  'Abstandstempomat': { en: 'Adaptive cruise control', tr: 'Adaptif hız sabitleyici' },
  'Alarmanlage': { en: 'Alarm system', tr: 'Alarm sistemi' },
  'Alufelgen': { en: 'Alloy wheels', tr: 'Alaşım jant' },
  'Ambiente-Beleuchtung': { en: 'Ambient lighting', tr: 'Ortam aydınlatması' },
  'Android Auto': { en: 'Android Auto', tr: 'Android Auto' },
  'Anhängerkupplung': { en: 'Tow bar', tr: 'Çeki demiri' },
  'Apple CarPlay': { en: 'Apple CarPlay', tr: 'Apple CarPlay' },
  'Behindertengerecht': { en: 'Wheelchair accessible', tr: 'Engelli kullanımına uygun' },
  'Beifahrer-Airbag Deaktivierung': { en: 'Passenger airbag deactivation', tr: 'Yolcu hava yastığı devre dışı' },
  'Beifahrerairbags': { en: 'Passenger airbags', tr: 'Yolcu hava yastıkları' },
  'Berganfahrassistent': { en: 'Hill start assist', tr: 'Yokuşta kalkış desteği' },
  'Bluetooth': { en: 'Bluetooth', tr: 'Bluetooth' },
  'Bordcomputer': { en: 'Trip computer', tr: 'Yol bilgisayarı' },
  'CD Player': { en: 'CD player', tr: 'CD çalar' },
  'DAB-Radio': { en: 'DAB radio', tr: 'DAB radyo' },
  'Dachreling': { en: 'Roof rails', tr: 'Tavan rayları' },
  'ESP': { en: 'ESP', tr: 'ESP' },
  'Elektr. Heckklappe': { en: 'Electric tailgate', tr: 'Elektrikli bagaj kapağı' },
  'Fahrerairbag': { en: 'Driver airbag', tr: 'Sürücü hava yastığı' },
  'Fernlichtassistent': { en: 'High-beam assist', tr: 'Uzun far asistanı' },
  'Freisprecheinrichtung': { en: 'Hands-free system', tr: 'Eller serbest sistemi' },
  'Frontscheibenheizung': { en: 'Heated windscreen', tr: 'Ön cam ısıtma' },
  'Getönte Scheiben': { en: 'Tinted windows', tr: 'Renkli camlar' },
  'Head-Up-Display': { en: 'Head-up display', tr: 'Head-up gösterge' },
  'ISOFIX': { en: 'ISOFIX', tr: 'ISOFIX' },
  'Induktionsladen': { en: 'Wireless charging', tr: 'Kablosuz şarj' },
  'Innenspiegel autom. abblendend': { en: 'Auto-dimming rear-view mirror', tr: 'Otomatik kararan iç dikiz aynası' },
  'Keyless entry': { en: 'Keyless entry', tr: 'Anahtarsız giriş' },
  'Keyless go': { en: 'Keyless go', tr: 'Anahtarsız çalıştırma' },
  'Klimaanlage': { en: 'Air conditioning', tr: 'Klima' },
  'Klimaautomatik': { en: 'Automatic climate control', tr: 'Otomatik klima' },
  'Kollisionswarner': { en: 'Collision warning', tr: 'Çarpışma uyarı sistemi' },
  'Komfortfahrwerk': { en: 'Comfort suspension', tr: 'Konfor süspansiyon' },
  'Kopfairbags': { en: 'Curtain airbags', tr: 'Perde hava yastıkları' },
  'Kurvenlicht': { en: 'Cornering lights', tr: 'Viraj aydınlatması' },
  'LED-Scheinwerfer': { en: 'LED headlights', tr: 'LED farlar' },
  'LED-Tagfahrlicht': { en: 'LED daytime running lights', tr: 'LED gündüz farları' },
  'Laserlicht': { en: 'Laser headlights', tr: 'Lazer farlar' },
  'Leasingfähig': { en: 'Available for leasing', tr: 'Leasinge uygun' },
  'Lederausstattung': { en: 'Leather upholstery', tr: 'Deri döşeme' },
  'Lederlenkrad': { en: 'Leather steering wheel', tr: 'Deri direksiyon' },
  'Lenkradheizung': { en: 'Heated steering wheel', tr: 'Direksiyon ısıtma' },
  'Lichtsensor': { en: 'Light sensor', tr: 'Işık sensörü' },
  'Lordosenstütze': { en: 'Lumbar support', tr: 'Bel desteği' },
  'Luftfederung': { en: 'Air suspension', tr: 'Havalı süspansiyon' },
  'Massagesitze': { en: 'Massage seats', tr: 'Masajlı koltuklar' },
  'Matrix LED Licht': { en: 'Matrix LED lights', tr: 'Matrix LED far' },
  'Metallic-Lackierung': { en: 'Metallic paint', tr: 'Metalik boya' },
  'Mittelarmlehne': { en: 'Centre armrest', tr: 'Orta kol dayama' },
  'Multifunktionslenkrad': { en: 'Multifunction steering wheel', tr: 'Çok fonksiyonlu direksiyon' },
  'Multimediasystem': { en: 'Multimedia system', tr: 'Multimedya sistemi' },
  'MwSt. ausweisbar': { en: 'VAT deductible', tr: 'KDV ayrıştırılabilir' },
  'Müdigkeitswarnsystem': { en: 'Driver fatigue warning', tr: 'Yorgunluk uyarı sistemi' },
  'Nachtsichtassistent': { en: 'Night vision assist', tr: 'Gece görüş asistanı' },
  'Navigationssystem': { en: 'Navigation system', tr: 'Navigasyon sistemi' },
  'Nebelscheinwerfer': { en: 'Fog lights', tr: 'Sis farları' },
  'Nichtraucherfahrzeug': { en: 'Non-smoker vehicle', tr: 'Sigara içilmemiş araç' },
  'Notbremsassistent': { en: 'Emergency brake assist', tr: 'Acil fren asistanı' },
  'Notrufsystem': { en: 'Emergency call system', tr: 'Acil çağrı sistemi' },
  'Pannenkit': { en: 'Tyre repair kit', tr: 'Lastik tamir kiti' },
  'Panoramadach': { en: 'Panoramic roof', tr: 'Panoramik tavan' },
  'Parkassistent selbstlenkend': { en: 'Self-steering park assist', tr: 'Otomatik park asistanı' },
  'Parksensor hinten': { en: 'Rear parking sensors', tr: 'Arka park sensörü' },
  'Parksensor vorne': { en: 'Front parking sensors', tr: 'Ön park sensörü' },
  'Radio': { en: 'Radio', tr: 'Radyo' },
  'Regensensor': { en: 'Rain sensor', tr: 'Yağmur sensörü' },
  'Reifendruckkontrolle': { en: 'Tyre pressure monitoring', tr: 'Lastik basınç kontrolü' },
  'Reserverad': { en: 'Spare wheel', tr: 'Yedek lastik' },
  'Rückfahrkamera': { en: 'Reversing camera', tr: 'Geri görüş kamerası' },
  'Schaltwippen': { en: 'Paddle shifters', tr: 'Direksiyondan vites' },
  'Scheinwerferreinigung': { en: 'Headlight washers', tr: 'Far yıkama' },
  'Schiebedach': { en: 'Sunroof', tr: 'Sunroof' },
  'Schiebetür': { en: 'Sliding door', tr: 'Sürgülü kapı' },
  'Seitenairbags': { en: 'Side airbags', tr: 'Yan hava yastıkları' },
  'Serviceheft': { en: 'Full service history', tr: 'Servis kitapçığı' },
  'Servolenkung': { en: 'Power steering', tr: 'Hidrolik direksiyon' },
  'Sitzbelüftung': { en: 'Ventilated seats', tr: 'Koltuk havalandırma' },
  'Sitzheizung hinten': { en: 'Heated rear seats', tr: 'Arka koltuk ısıtma' },
  'Sitzheizung vorne': { en: 'Heated front seats', tr: 'Ön koltuk ısıtma' },
  'Skisack': { en: 'Ski hatch', tr: 'Kayak geçişi' },
  'Sommerreifen': { en: 'Summer tyres', tr: 'Yaz lastiği' },
  'Soundsystem': { en: 'Sound system', tr: 'Ses sistemi' },
  'Sperrdifferential': { en: 'Limited-slip differential', tr: 'Kilitli diferansiyel' },
  'Sportfahrwerk': { en: 'Sports suspension', tr: 'Spor süspansiyon' },
  'Sportpaket': { en: 'Sports package', tr: 'Spor paket' },
  'Sportsitze': { en: 'Sports seats', tr: 'Spor koltuklar' },
  'Sprachsteuerung': { en: 'Voice control', tr: 'Sesli komut' },
  'Spurhalteassistent': { en: 'Lane keeping assist', tr: 'Şerit takip asistanı' },
  'Spurwechselassistent': { en: 'Lane change assist', tr: 'Şerit değiştirme asistanı' },
  'Stahlfelgen': { en: 'Steel wheels', tr: 'Çelik jant' },
  'Standheizung': { en: 'Auxiliary heating', tr: 'Park ısıtıcısı' },
  'Start/Stop-Automatik': { en: 'Start/stop system', tr: 'Start/stop sistemi' },
  'Tagfahrlicht': { en: 'Daytime running lights', tr: 'Gündüz farları' },
  'Teilautonomes Fahren': { en: 'Semi-autonomous driving', tr: 'Yarı otonom sürüş' },
  'Tempomat': { en: 'Cruise control', tr: 'Hız sabitleyici' },
  'Totwinkelassistent': { en: 'Blind spot assist', tr: 'Kör nokta asistanı' },
  'Touchscreen': { en: 'Touchscreen', tr: 'Dokunmatik ekran' },
  'Traktionskontrolle': { en: 'Traction control', tr: 'Çekiş kontrolü' },
  'Verkehrszeichenerkennung': { en: 'Traffic sign recognition', tr: 'Trafik işareti tanıma' },
  'Virtual Cockpit': { en: 'Virtual cockpit', tr: 'Dijital gösterge paneli' },
  'WLAN': { en: 'Wi-Fi', tr: 'Wi-Fi' },
  'Wegfahrsperre': { en: 'Immobiliser', tr: 'Immobilizer' },
  'Windschott': { en: 'Wind deflector', tr: 'Rüzgar kesici' },
  'Winterpaket': { en: 'Winter package', tr: 'Kış paketi' },
  'Winterreifen': { en: 'Winter tyres', tr: 'Kış lastiği' },
  'Xenon': { en: 'Xenon', tr: 'Xenon' },
  'Zentralverriegelung': { en: 'Central locking', tr: 'Merkezi kilit' },
  'elektr. Fensterheber': { en: 'Electric windows', tr: 'Elektrikli camlar' },
  'elektr. Sitze': { en: 'Electric seats', tr: 'Elektrikli koltuklar' },
  'elektr. Spiegel': { en: 'Electric mirrors', tr: 'Elektrikli aynalar' },
}
